version: '3.7'
services:
# Postgresql
  postgres:
    image: postgres:latest
    ports:
      - "8001:5432"
    environment:
      - PG_PRIMARY_USER= postgres
      - PG_PRIMARY_PASSWORD= my-secret-password
      - POSTGRES_PASSWORD=Password09!
      - POSTGRES_DB=postgres_db
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "8002:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  db_data:
    driver: local
